#ifndef Demo_codeObfuscation_h
#define Demo_codeObfuscation_h
//confuse string at Sun May  7 16:42:47 CST 2017
#define startEngine vcVvINfHHLskkUbO
#define evaluateScriptWithPath phmSLPNWuILGSSmy
#define handleException ihSXsXXJYnBggGbh
#define handleMemoryWarning lsXZJItjrSTmnivJ
#define defineStruct oqVJWujXWdOpIwcb
#define addExtensions bYZlxtlVEuwIfdAY
#define formatOCToJS XeUbGgkvoPHGKENk
#define formatJSToOC QGtcBOaYDyRBdVmm
#define formatPointerOCToJS vFcMkZxRIkNmnsCU
#define formatRetainedCFTypeOCToJS gWzikYcRyiPGskdO
#define formatPointerJSToOC LIVxGWdeByIchTOc
#define includedScriptPaths CkKaropgEonSURcM
#define getStructDataWidthDict SOZsYBHkYVXtJylK
#define boxAssignObj NFYhYmHnOgNwFjxQ
#define boxWeakObj rVQKqCQWRhTbOdrD
#define boxClass XrFURKLixtUAnYBq
#define boxPointer BmlapHWCQbusTkhP
#define boxObj jrFVYLcUKUyBdvBT
#define sizeOfStructTypes ptVxKfqjmNjpNIru
#define getDictOfStruct rnfADbAHINPylthJ
#define structDefine nwjdQonYTsKJzQud
#define registeredStruct SPaChoLaIFBQOFGR
#define overideMethods pXZVGmmcfIulDdSG
#define unboxPointer qJSSoIAwGHKkHcno
#define unboxClass hoHULYyQtbxxZjPd
#define jp_methodSignatureForSelector lHkBgbZHRvOiJQSY
#define jp_fixMethodSignature FPtnpUhEbppHnHjh
#define JPBoxing CKsPuCVwknFXAgJf
#define JPBlock kdMLIpDtKIlignfo
#define JPBlockWrapper rZDejxyFzanYUORD
#define JPCFunction gOHLPisxZEpprvqG
#define JPMemory hqwRjLRqHbpquEfa
#define JPStructPointer qDMtFrayDGinqleU
#define JPCGBitmapContext WBPZtDSDOAFWcOID
#define JPCGColor QOMFRdbxHpzAJJlH
#define JPCGContext AUtoFhFDtRFbfvWf
#define JPCGGeometry snOUuHOgDLhbZBmz
#define JPCGImage YvCMsRPhUfRjsTBx
#define JPCGPath VafUcpIdepHydAPv
#define JPCGTransform FRvJFHYfGJRHfguc
#define JPCoreGraphics zapJwwAlYchFxLpF
#define JPUIGeometry MfgukwmSZRwWTUvv
#define JPUIGraphics aJJYATemBueqpoxC
#define JPUIImage EqdFakfksHMzDqWn
#define JPUIKit OAIBuHPKhsjLEPxs
#define JPCleaner jfmZEmcbvszJDnGa
#define JPDispatch FPELYgnCTnzqZHHm
#define JPMethodSignature qDTxSzWyVANUnfTP
#define JPLocker KaZWzaGVtvQsHpYg
#define JPNumber EaXqBatvIrGQAHLg
#define JPKeyCommands pdHtNxEPmBTopEhu
#define SGDirWatchdog mBDLqYxyevrjkuOa
#define JPProtocol OxxYFgOkxNBJKwnX
#define JPSpecialInit jPAdxpKyuDcBXbeH
#define JPEngine NTXRumqmQhIboVzm
#define JPLoader niCGKAgcqszKiQSP
#define JPLoaderInclude PeruJzHBvEteepXJ
#define JPLoaderTestInclude OzTAtpTuxiWYJfVR
#define JPExtension izOwStRYwneguWbw
#define JPPlayground ALGQyxdJIKcxlpJX
#define JPDevErrorView OgYxXgalXAMXfaQU
#define JPDevMenu ejGHflhVZcXAIWlO
#define JPDevMenuItem ozAEtHXlosqBPCmQ
#define JPDevTipView FAvEdwKDHbugHOvQ
#define JPDevMenuDelegate xaIRLGFpvWKUUIXt
#endif
